# Site settings
title: Words
email: emilio@crisal.io
emails:
  - emiliocobos@usal.es
  - ecoal95@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Code is poetry
baseurl: "/words"
url: "http://crisal.io"
twitter_username: ecbos_
github_username: emilio

# Build settings
future: true
# markdown: redcarpet
